# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azureserviceconnection'
    subscriptionId: '63e5f9c9-9bf0-4724-b30a-5facf56021ce'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test-RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Incremental'
